import { ReactNode } from 'react';
import { ThemeProvider } from '../common/provider/themeProvider';
import theme from '../common/styles/theme';
import Header from '../templates/header';
import globals from './globals';
import { Global } from '../common/provider/styleProvider';

export const metadata = {
  title: 'BookHistory',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body style={{ background: '#0C0C0C' }}>
          <Global styles={globals} />
          <Header />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
