import React, { ReactNode } from 'react';
import theme from '@/app/_lib/styles/theme';
import Header from '@/app/_components/header';
import globals from './globals';
import Global from '@/app/_lib/provider/styleProvider';
import ThemeProvider from '@/app/_lib/provider/themeProvider';
import AuthProvider from './_lib/provider/authProvider';
import ErrorBoundary from './_components/ErrorBoundary';

export const metadata = {
  title: 'BookHistory',
  description: 'Generated by Next.js',
};

const RootLayout = ({
  children,
}: {
  children: ReactNode
}) => {
  return (
    <html lang="en">
      <body style={{ background: '#141414' }}>
        <ErrorBoundary>
          <ThemeProvider theme={theme}>
            <AuthProvider>
              <Global styles={globals} />
              <Header />
              {children}
            </AuthProvider>
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
};

export default RootLayout;
